### ISSUE TITLE
The app shows error in the code but after compiling it works fine

### ISSUE THREAD

**Issue by zohaibkhan987** [Deenu143/CodeAssist-ALPHA-0.2.9#11]
As we all know after placing the dependency in build.gradle file
We can use the library
But the app editor does not detect any library
It just shows up errors including the right errors
Also in its xml file editor
There's no such RadioGroup or RadioButton Switch and text attribute for switch
Also many more 

Please fix these

**Comment by Deenu143** [comment]
When adding dependencies to build.gradle file refresh module to sync dependencies
