### ISSUE TITLE
Copy /Paste Bug

### ISSUE THREAD

**Issue by abodinagdat16** [Deenu143/CodeAssist-ALPHA-0.2.9#13]
**Describe the bug**
I get this error in below when i copy / paste text some times :
ERROR: cannot access java.lang.ClassNotFoundException
  bad class file: /data/user/0/com.tyron.code/files/rt.jar(/java/lang/ClassNotFoundException.class)
    unable to access file: java.nio.channels.ClosedChannelException
    Please remove or make sure it appears in the correct subdirectory of the classpath. [PlayerView.java:143]
**To Reproduce**
1. Copy any text
2. Paste it (Only some times happen when i paste or copying the text );
3. And some time if there are so many issues in the code 

**Smartphone **
 - Device: Samsung s23 ultra
 - OS: android 14(rooted)

**Additional context**

**Comment by Deenu143** [comment]
Yeah i get the same issue some times the rt jar is exist but java completion library not able to find them
You can reopen the CA to solve the problem.
