### ISSUE TITLE
several gliches

### ISSUE THREAD

**Issue by ahsim** [Deenu143/CodeAssist-ALPHA-0.2.9#2]
I notice a lot of glitches. Maybe you can fix it?
I can add some screenshots and notes if you agree.

**Comment by Deenu143** [comment]
> I notice a lot of glitches. Maybe you can fix it? I can add some screenshots and notes if you agree.

What's that

**Comment by Deenu143** [comment]
Not responding from user

**Comment by scto** [comment]
Havent any glitches, you do a fantastic job bro
