### ISSUE TITLE
Redeclaration Error

### ISSUE THREAD

**Issue by bassem-saeed** [Deenu143/CodeAssist-ALPHA-0.2.9#4]
Hi,
I get Redeclaration error in code assist at my project:
![Screenshot_٢٠٢٣٠٤١١-٢٢٥٧٥١_CodeAssist](https://user-images.githubusercontent.com/65798784/231286535-4d5862f9-2895-4ae3-ade8-bc952c49b082.jpg)
See the first and last error ,when I clicked on the classes at the first and last error I got this:
![Screenshot_٢٠٢٣٠٤١١-٢٢٥٩٠٣_CodeAssist](https://user-images.githubusercontent.com/65798784/231286761-27ffac28-ff06-45b8-89be-25bab4dc272c.jpg)
Like you see there is two paths for one class

Please fix the problem

**Comment by Deenu143** [comment]
Check your Class and make sure you have one class 
Also check for the projects maybe it is taking from another root projects
It seems your using an older version try with the latest version from the commits

**Comment by Deenu143** [comment]
No response from user
