### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by zohaibkhan987** [Deenu143/CodeAssist-ALPHA-0.2.9#7]
Hello dear developers
I am an android 11 user
I am always looking forward for new updates but this new update is not installing in my device 
I don't know why i tried every possible thing
For example Clearing data and cache of my package installer, Modifiying its android manifest file but sadly nothing worked as expected
I used the previous versions but now in this device i am facing the problem of apk not istalled
Please fix it if this is issue with you app
But if it's not just forgive me for my awfull issue report

Device name InfinixHOT10S
Android version Android 11

Thanks you so much
Regards @M_Zohaib

**Comment by Deenu143** [comment]
@zohaibkhan987 I have the same device model which you have described
It is installing on my device without any problems
Make sure you have uninstalled the old version without save data option while uninstalling
