### ISSUE TITLE
All activity text erases while we try to slide erase some text

### ISSUE THREAD

**Issue by zohaibkhan987** [Deenu143/CodeAssist-ALPHA-0.2.9#9]
In every keyboard we have two option while to erase the whole e.g function by simply long clicking the erase button in the keyboard
And the second option is to quickly erase most of the text by just moving your finger from the erase buttom to all the way left
But this quick shortcut does not work for it
It just removes every single text in the activity or xml file
Please do a fix

**Comment by Deenu143** [comment]
Try using another keyboard i am using Gboard I have no issues
